default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: petadmin_development

test:
  <<: *default
  database: petadmin_exchance_test

production:
  <<: *default
  database: petadmin_exchance_production